name: Close PRs
on: [pull_request]

jobs:
  close_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: actions/github-script@v7
        with:
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: 'closed'
            })
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "Pull requests are not accepted for this repository."
            })
